services:
  - type: web
    name: todo-list-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
  
  - type: pserv
    name: todo-db
    env: postgresql
    region: oregon
    plan: free
    databaseName: todolist